### ISSUE TITLE
crash when in inventory

### ISSUE THREAD

**Issue by Diegorj08** [P3pp3rF1y/SophisticatedCore#154] opened 2023-07-28 04:48 UTC
When I'm in the inventory it crashes randomly, it's already happening twice

First crash:
https://pastebin.com/3DrH0ZXx
Second crash:
https://pastebin.com/A2JEXV7n

**Comment by P3pp3rF1y** [comment] 2023-07-28 07:37
this is a duplicate of #150

**Closed as not planned by P3pp3rF1y** 2023-07-28 07:37 UTC
