### ISSUE TITLE
Crash when loading the game

### ISSUE THREAD

**Issue by WanghanMarcCui** [P3pp3rF1y/SophisticatedCore#85] opened 2023-04-04 13:03 UTC
The game crashes when I try to load it.

I'm using forge 1.18.2

Error message:
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle sophisticatedcore:jukebox_note

[crash-2023-04-04_14.52.53-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/11148803/crash-2023-04-04_14.52.53-client.txt)

**Comment by P3pp3rF1y** [comment] 2023-07-09 07:29
I haven't gotten a single other report for this from anyone else, it works in dev environment and also works in modpacks I play so I would think this is caused by some mod in your pack that messes with particles or by corrupted download of my mod or something similar. if after new download this is still happening you would need to figure out what mod addition makes it fail like this.
you may also be able to fing something more in latest.log, there may very likely be another issue happening before this one which causes particle data to not load.

**Comment by P3pp3rF1y** [comment] 2023-09-01 23:02
closing given that no additional info was provided and I haven't seen any other report either

**Closed as completed by P3pp3rF1y** 2023-09-01 23:02 UTC
Labels: question
